name: Android CI
env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false"
on:
  push:
    branches: [ master, develop, trunk ]

jobs:
  ci-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.5

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true

      - name: Run build
        run: ./gradlew build

      - name: Generate merged report by Kover
        run: ./gradlew koverMergedReport

      - name: Add coverage report to PR
        id: kover
        uses: mi-kas/kover-report@v1
        with:
          path: report/test-coverage/report.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Test Coverage

      - name: Generate test coverage badge
        uses: emibcn/badge-action@v2.0.2
        with:
          label: Test Coverage
          status: ${{ steps.kover.outputs.coverage-overall }}%
          color: FFB341
          path: assets/coverage.svg

      - name: Push test coverage badge
        continue-on-error: true # continuation when up-to-date.
        run: |
          git config user.name "sungbinland-bot"
          git config user.email "sungbinland.project@gmail.com"
          git add assets/coverage.svg
          git commit -m "[CI] update test coverage badge"
          git push
